version: "3.8"

name: todo-microservices

services:
  todo:
    container_name: todo
    build:
      context: ../..
      dockerfile: cmd/todo/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  auth:
    container_name: auth
    build:
      context: ../..
      dockerfile: cmd/auth/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  notification:
    container_name: notification
    build:
      context: ../..
      dockerfile: cmd/notification/Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  user:
    container_name: user
    build:
      context: ../..
      dockerfile: cmd/user/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
